function G(a,d,e){function h(){0!=I&&(K=(new Date).getTime()-I)}function l(f){F=F|f;B.narme=F}function m(f){p.a("l2("+f+")");E=E|f;T()?(h(),I=0):0==I&&(I=(new Date).getTime());B.narm=E;p.a("l2e")}function q(f){L=L|f;B.naral=L}var p=new P,c=e&&e.dvObj||window.$dv,k=e&&e.impressionId||window.$uid,w=window.Pf||d,r=Array(w.hb),g=w.Wa/w.Wb+1,b=null,t="",v={},f=0,u=Array(w.hb),n={da:{I:null,J:null,D:null,C:null,Oe:!1},g:{v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,Oe:!1},va:{zb:null,yb:null},
Fb:0},x={},C={},A,y,z={},N={},J=null,Q=!1;this.Cb=function(f){if(null==J||1==J||8==J)J=f};for(d=0;d<w.hb;d++)u[d]="b"+d;var D={};e&&c&&c.CommonData&&(D.ctx=e.jb,D.cmp=e.ib,D.btreg=e.btreg,D.btadsrv=e.Qa,D.uid=e.ob,D.brid=c.CommonData.BrowserId,D.brver=c.CommonData.BrowserVersion,D.tstype=c.CommonData.Scenario);D.jsver=a?a:null;var B={},H={},I=0,K="",M="",L=0,E=0,F=0,O=0;this.Oc=function(){return I};this.rd=function(f){O=O|f;B.vct=O};this.qd=function(f){b=f;H.strp=b;this.qd=function(){}};this.$b=function(){return(new Date).getTime()};
var U=this.$b();this.Ee=function(){return U};this.qf=function(){E=E&-3;F=F&-2;F&=-3};this.Bb=function(){m(2)};this.Bf=function(){l(8);this.pc()};this.pc=function(){m(4)};this.md=function(){q(8);this.Bb()};this.xd=function(f){q(16);B.dbg9=f};this.yd=function(){q(1)};this.zf=function(){this.Bb();l(1)};this.yf=function(){this.Bb();l(2)};this.Za=function(f,g){m(8);M=p.xe(f,g)};this.vf=function(){p.a("l1");E=E&-3;m(1);p.a("l1e")};this.pd=function(){m(16)};this.re=function(){return r};this.nd=function(b,
a){k=k||e&&e.impressionId||window.$uid;p.a("ie15");if(0<=b.j){var c=Math.floor(b.j/w.Wb);0<b.j%w.Wb?c++:0<b.j&&c++;isNaN(r[c])&&(r[c]=0);r[c]+=a;b.P&&c>=g||0==b.P&&6<=c?f+=a:(timeStampTotalBuckets=f=0,this.Cb(7))}p.a("ie15e")};this.xf=function(f){var b=f.Vc;null!=f.Vc&&(x.advisonl=b);null!=f.Uc&&(x.adabvvponl=f.Uc);B.dbg8="CSS1Compat"===document.compatMode?1:0;p.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&(B.dbg10=document.documentMode);p.a("ff52e")};this.Ya=function(f){p.a("ie14");
null!=f&&(N.adbtftopg=f)};this.wf=function(f){null!=f&&(n=f)};this.od=function(f){p.a("ie19");this.wf(f.s);this.Df();p.a("ie19e")};this.Bd=function(){null!=n.da.I&&(z.vptoscrx=Math.round(n.da.I));null!=n.da.J&&(z.vptoscry=Math.round(n.da.J));null!=n.da.D&&(z.vpwdth=Math.round(n.da.D));null!=n.da.C&&(z.vphgt=Math.round(n.da.C));null!=n.g.v&&(z.adtovpx=Math.round(n.g.v));null!=n.g.u&&(z.adtovpy=Math.round(n.g.u));null!=n.g.K&&(z.adtopgx=Math.round(n.g.K));null!=n.g.L&&(z.adtopgy=Math.round(n.g.L));
null!=n.g.G&&(z.adtoscrx=Math.round(n.g.G));null!=n.g.H&&(z.adtoscry=Math.round(n.g.H));null!=n.va.zb&&(z.scrwdth=Math.round(n.va.zb));null!=n.va.yb&&(z.scrhgt=Math.round(n.va.yb));z.almesind=n.Fb};this.Cd=function(){if(A&&y){var f=n.g.o,b=n.g.m;A*y<f*b&&(C.dvp_adwdth=Math.round(A),C.dvp_adhgt=Math.round(y),!Q&&(1>=A||1>=y)&&1<f&&1<b&&($dv.registerEventCall(k,{adwdth:Math.round(f),adhgt:Math.round(b)}),Q=!0),A=f,y=b)}else A=null!=n.g.o?n.g.o:null,y=null!=n.g.m?n.g.m:null;null!=A&&(C.adwdth=Math.round(A));
null!=y&&(C.adhgt=Math.round(y))};this.Df=function(){h();for(var f=0;f<r.length;f++)r[f]&&(v[u[f]]=r[f]);this.Bd();this.Cd();p.F(z,x);p.F(z,C);p.F(z,N)};this.Mc=function(){if(1E3<=f)return!0;this.Cb(8);return!1};this.Be=function(f){var b={};k=k||e&&e.impressionId||window.$uid;var g=-1,a=p.ye();try{c&&c.tags[k]&&c.tags[k].getTimeDiff&&(g=c.tags[k].getTimeDiff())}catch(r){}var n=[];p.F(b,D);switch(f){case 1:t=g;p.F(b,H);p.F(b,B);b.napt=K;p.F(b,z);b.dvp_log=a;b.napr=M;b.ismms=t;b.isumms=g;break;case 2:p.F(b,
H);p.F(b,B);b.napt=K;p.F(b,z);b.dvp_log=a;b.napr=M;b.isnmms=g;break;case 3:b.istoms=g,b.nvr=J;case 4:case 8:p.F(b,H);p.F(b,N);p.F(b,C);b.isbxdms=g;p.F(b,v);b.nvr=J;break;case 5:p.F(b,H);p.F(b,N);p.F(b,C);p.F(b,x);b.ismms=t||g;b.isiabvms=g;b.isuiabvms=g;break;case 16:p.F(b,H);p.F(b,B);b.napt=K;b.dvp_log=a;b.napr=M;b.ishems=g;break;case 7:return n.join("");default:p.F(b,H),p.F(b,v),p.F(b,B),p.F(b,x),b.napt=K,b.dvp_log=a,b.napr=M}b.evid=f;b.ctime=this.$b();return b};this.qe=function(){p.a("ie17");for(var f=
[],b=0;b<w.hb;b++)f[b]=r[b]?r[b]:0;return f};var T=this.Gc=function(){return 2==(E&2)&&8!=(L&8)||4==(E&4)||8==(F&8)&&8==(L&8)?!1:!0};this.hf=function(f){p.a("l3");f=p.ba(f);p.a("cm3e");f&&(B.dbg5=f.w,B.dbg6=f.h);p.a("l3e")};return this}function R(a,d){var e=new P,h=a&&a.impressionId||window.$uid;this.ca=function(a,m){if(d){var q=d.Be(a);m&&e.F(q,m);var p=!1;if(4==a||8==a)p=!0;this.ld(h,q,p)}};this.ld=function(a,d,e){$dv&&$dv.registerEventCall&&a&&$dv.registerEventCall(a,d,null,!e,e)}}
function S(){this.ca=function(){};this.ld=function(){}}
function V(a,d,e,h){function l(){if(1==n){try{for(var b in f)u.removeChild(f[b]);t.document.body.removeChild(u)}catch(g){}n=!1}}function m(f){f=f||0;var b=c(0);b.Yc()?7<b.nb()?(l(),C=x=n=!1):(n=!0,x=!1):20>f?(f++,setTimeout(m,50,f)):(n=x=C=!1,l())}function q(f){$dv&&$dv.tags&&$dv.tags[h]&&$dv.tags[h].getTimeDiff&&$dv.tags[h].getTimeDiff();if(null!==f.eb)for(var b=0;b<f.eb.length;b++){var g=c(b).nb();0==b?g>A&&(A=g):g>y&&(y=g)}}function p(f){for(var b=!0,g=0;13>=g;g++)var k=c(g),b=b&(null!==k&&k.Yc());
if(!b)return null;f.Dc=0;f.nc=0;f.mc=0;f.gc=0;f.Ca=0;f.eb=Array(13);b=c(0).nb();for(g=1;13>=g;g++)if(k=5<Math.abs(c(g).nb()-b),f.eb[g]=k)switch(f.Dc++,g){case 2:case 3:case 4:case 5:f.nc++;break;case 6:case 7:case 8:case 9:f.mc++;break;case 10:case 11:case 12:case 13:f.gc++}if(13===f.Dc)return f.Ca=100,q(f),!0;b=f.eb;if(!1===b[1]){if(3<=f.gc||3<=f.mc||3<=f.nc)return q(f),null;f.Ca=0;q(f);return!1}if(!0===b[1]&&(!0===b[2]&&!0===b[3]||!0===b[2]&&!0===b[4]||!0===b[3]&&!0===b[5]||!0===b[4]&&!0===b[5])||
!0===b[1]&&4==f.mc||!0===b[1]&&4==f.gc&&1<=f.nc)return f.Ca=50,q(f),!0;if(b[2]&&b[5]&&!(b[6]&&b[10]&&b[1]&&b[13]&&b[9])||b[4]&&b[3]&&!(b[8]&&b[12]&&b[1]&&b[11]&&b[7]))return q(f),null;f.Ca=0;q(f);return!1}function c(b){b=f[b];var g=null;b&&(g=b.contentWindow);return g}function k(){for(var b=v.getBoundingClientRect(),k=b.width,a=b.height,c=k/(1+r),n=a/(1+r),t=k/r,w=a/r,u=0;13>=u;u++){var d=b.left,e=b.top;switch(u){case 0:e=d=-1E5;break;case 1:d+=(k-g)/2;e+=(a-g)/2;break;case 3:d+=k-g;break;case 4:e+=
a-g;break;case 5:d+=k-g;e+=a-g;break;case 6:d+=(k-t)/2;e+=(a-w)/2;break;case 7:d+=(k-t)/2+t;e+=(a-w)/2;break;case 8:d+=(k-t)/2;e+=(a-w)/2+w;break;case 9:d+=(k-t)/2+t;e+=(a-w)/2+w;break;case 10:d+=(k-c)/2;e+=(a-n)/2;break;case 11:d+=(k-c)/2+c;e+=(a-n)/2;break;case 12:d+=(k-c)/2;e+=(a-n)/2+n;break;case 13:d+=(k-c)/2+c,e+=(a-n)/2+n}6<=u&&(d-=g/2,e-=g/2);var x=f[u];x.style.left=d+"px";x.style.top=e+"px"}}function w(){if(null!=v&&null!=v.parentNode){x=!0;u=t.document.createElement("div");t.document.body.appendChild(u);
for(var b=0;13>=b;b++){var a=t.document.createElement("iframe");a.width=g;a.height=g;a.style.position="absolute";a.frameBorder="0";a.style.visibility="hidden";a.style.zIndex=-9999999;a.style.display="block";a.src="javascript:no=false;yes=true;("+function(){window.af={Zd:100};window.Kc=no;window.bb=0;window.Tc=0;window.ad=0;window.Sf=no;window.nb=function(){return window.ad};window.Yc=function(){return window.Kc};window.Ve=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Rb=function(){window.bb++;window.Ve(window.Rb,document)};window.Rb();setInterval(function(){10>window.bb&&window.Rb();window.ad=window.bb-window.Tc;window.Tc=window.bb},window.af.Zd);window.setTimeout(function(){window.Kc=yes},250)}.toString()+")();";u.appendChild(a);f.push(a)}k()}}var r=Math.sqrt(2),g=1,b=new P,t=null,v=null,f=[],u,n=!1,x=!1,C=b.ub(a,d,e);0==b.Ua()&&(g=8);var A=0,y=0;this.Ke=function(){0==x&&(0==(this.Va()&&(null!=v&&b.Xc(v,t)?!0:!1))?n=!1:(w(),
m()))};this.Va=function(){return C};this.Re=function(){return n};this.sd=function(f,b){t=f;v=b;this.Ke()};this.He=function(){if(0==n)return null;var f={};return null==p(f)?null:f.Ca}}
function W(a,d,e,h,l,m,q,p){this.b=new P;this.window=a;this.c=d;this.R=e;this.M=h;this.Y=q&&q.Enums.BrowserId||window.$dv.Enums.BrowserId;this.V=q&&q.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.N=l;this.ec=m;this.fa=null;this.Sc=this.window?this.b.vb(this.window.top):this.b.vb(window.top);this.Ne=this.R!=this.V.CrossDomain&&this.b.lb("ofs")&&this.Sc;this.fa=new V(this.R,this.M,q,p);null!=this.fa&&this.fa.Va()&&this.fa.sd(this.window,this.c);this.qb=this.wb=this.pa=null;this.rb=!1;
var c=0;this.ha={Nd:1,Od:2,Id:4,Kb:8,Hd:16,Lb:32,Md:64};this.oc=function(k,a,c,g){if(g&&g.insertBefore&&g.firstChild&&(k=this.window.document.createElement(k))){for(var b in a)k[b]=a[b];for(b in c)k.style[b]=c[b];g.insertBefore(k,g.firstChild);return k}return null};this.oe=function(k,a,c){var g=this.window.top,b=k.width,t=k.height;0>c.left?(b=k.width-Math.abs(c.left),0>a.Aa&&(b-=Math.abs(a.Aa))):0>a.Aa&&(b=k.width-Math.abs(a.Aa)+c.left,b=b>k.width?k.width:b);var d=k.width,f=Math.min(this.b.ya(g.window).clientWidth,
g.innerWidth),u=screen.availWidth-f-a.Aa,n=0;b<d?(d=b,n=f-b,0>a.Aa&&(n-=Math.abs(a.Aa))):n=f-d-c.left;0>n?(b=d-Math.abs(n),0>u&&(b-=Math.abs(u))):0>u&&(b=d-Math.abs(u)+n,b=b>d?d:b);a=screen.availHeight-a.rf-g.outerHeight;g=Math.min(this.b.ya(g.window).clientHeight,g.innerHeight)-k.height-c.top;0>g?(t=k.height-Math.abs(g),0>a&&(t-=Math.abs(a))):0>a&&(t=k.height-Math.abs(a)+g,t=t>k.height?k.height:t);0>c.top&&(t-=Math.abs(c.top));return{Gf:b,Hf:t}};this.Zb=function(a,c,r,g){var b=r.D,t=r.C,d=0;r=0;
var f={width:c.right-c.left,height:c.bottom-c.top};if(0>c.bottom||0>c.right||c.top>t||c.left>b||0>=f.width||0>=f.height)return 0;0>c.top?Math.abs(c.top)>=f.height?d=0:(d=f.height+c.top,d>t&&(d=t)):d=c.top+f.height>t?t-c.top:f.height;0>c.left?Math.abs(c.left)>=f.width?r=f.width:(r=f.width+c.left,r>b&&(r=b)):r=c.left+f.width>b?b-c.left:f.width;this.Ne&&(a=this.oe(f,a,c),r=a.Gf,d=a.Hf);return 0>=r||0>=d?0:Math.round(r*d/(f.width*f.height)*(g?f.width*f.height/((g.right-g.left)*(g.bottom-g.top)):1)*100)};
this.Yb=function(a,c){try{var r={x:a.offsetLeft,y:a.offsetTop},g;a.offsetParent?(g=this.Yb(a.offsetParent,c),r.x+=g.x,r.y+=g.y):c!=c.parent&&this.b.Mb(c,c.parent)&&(g=this.Yb(c.frameElement,c.parent),r.x+=g.x,r.y+=g.y);return r}catch(b){return{x:null,y:null}}};this.na=function(a){if(this.R==this.V.CrossDomain)if(this.b.ua(this.window)&&this.window.$sf.ext.geom)this.na=function(){var f=this.b.Ka(this.window),b=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-
parseInt(f.win.h):this.N.Explorer.W,g={D:null,C:null,I:null,J:null,i:!1};g.D=parseInt(f.win.w);g.C=parseInt(f.win.h);g.I=parseInt(f.win.l);g.J=parseInt(f.win.t)+b;g.i=!0;return g};else if(this.M.X==this.Y.Firefox)this.na=function(){var f=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,b=f?0:this.window.screenX-screen.left,f=f?0:this.window.screenY-screen.top,g={D:null,C:null,I:null,J:null,i:!1};g.D=this.window.outerWidth;g.C=this.window.outerHeight-this.N.Firefox.W;g.I=b;g.J=
f+this.N.Firefox.W;g.i=!0;return g};else if(this.b.jc(this.window)){var c=this;this.window.context.observeIntersection(function(f){f.forEach(function(f){c.pa=f})});this.na=function(){var f={D:null,C:null,i:!1,I:null,J:null};null!=this.pa?(f.D=this.pa.rootBounds.width,f.C=this.pa.rootBounds.height):(f.D=0,f.C=0);f.i=!0;return f}}else if(this.M.X==this.Y.IE&&/^[11|12]/.test(this.M.ta))this.na=function(){var f=-8==this.window.screenY&&-8==this.window.screenX,b=f?0:this.window.screenX,f=f?0:this.window.screenY,
g={D:null,C:null,I:null,J:null,i:!1};g.D=this.window.outerWidth;g.C=this.window.outerHeight-this.N.Explorer.W;g.I=b;g.J=f+this.N.Explorer.W;g.i=!0;return g};else if(this.M.X==this.Y.IE&&/[6-9]|[10]/.test(this.M.ta)){var r=this.oc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,je:0,We:"0",Xe:"0"},{display:"inline",position:"absolute",top:0,left:0,Ff:"none",zIndex:0,border:0},this.window.document.body),g=this.oc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,je:0,We:"0",Xe:"0"},{display:"inline",
position:"absolute",top:0,left:0,Ff:"none",zIndex:0,border:0},this.window.document.body),b=g.contentWindow||g.window||g.contentDocument.window||g.contentWindow.window||this.window.Kf,t=r.contentDocument||r.contentWindow.document,r=g.contentDocument||g.contentWindow.document,d="<html><head><script >window.onload = "+function(f){f&&(window.event=f);isFinite(String(window.event.clientY))&&(parent.Ra={Pb:window.event.clientY,Ob:window.event.clientX,Ad:window.event.screenY-window.event.clientY-window.screenY})}.toString()+
"; \x3c/script></head><body></body></html>",g='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(f){f&&(window.event=f);isFinite(String(window.event.clientY))&&(parent.qa={Pb:window.event.clientY,Ob:window.event.clientX,Ga:window.event.screenY-window.event.y,Fa:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";r.open("text/html","replace");r.write(g);r.close();
t.open("text/html","replace");t.write(d);t.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.na=function(){b.runMoM();t.open("text/html","replace");t.write(d);t.close();var f=this.window.qa,g=this.window.Ra,a=screen.availWidth,c=screen.availHeight,g=g?g.Ad:this.N.Explorer.W;if(f){var k=f.Fa,r=f.Ga;f.Fa>=a&&(f.Fa-=a);f.Ga>=c&&(f.Ga-=c);var e={D:null,C:null,I:null,J:null,i:!1};e.D=this.window.outerWidth?this.window.outerWidth-
20:a-f.Fa-20;e.C=this.window.outerHeight?this.window.outerHeight-g-10:c-f.Ga-10;e.I=k;e.J=r;e.i=!0}else e={D:null,C:null,I:null,J:null,i:!1},e.D=this.window.outerWidth?this.window.outerWidth-20:a-20,e.C=this.window.outerHeight?this.window.outerHeight-g-10:c-10,e.I=null,e.J=null,e.i=!1;return e}}else this.b.tb()?(this.hd(),this.na=function(){this.rb||this.hd();var f={D:null,C:null,I:null,J:null,i:!1};f.D=this.window.outerWidth;f.C=this.window.outerHeight-this.N.Chrome.W;f.i=!1;return f}):this.na=this.M.X==
this.Y.Chrome?function(){var f={D:null,C:null,I:null,J:null,i:!1},b=!1;try{f.D=this.window.frameElement.offsetParent.parentNode.clientWidth,f.C=this.window.frameElement.offsetParent.parentNode.clientHeight,b=!0}catch(g){}f.I=this.window.screenX;f.J=this.window.screenY;f.i=b;return f}:null!=this.fa&&this.fa.Va()?function(){var f={D:null,C:null,I:null,J:null,i:!1};f.D=this.window.outerWidth;f.C=this.window.outerHeight-this.N.Safari.W;f.i=!1;return f}:function(){return{D:null,C:null,I:null,J:null,i:!1}};
else this.na=function(){var f,b,g=this.window.top;void 0!=g.mozInnerScreenX&&null!=g.mozInnerScreenX?(f=g.mozInnerScreenX,b=g.mozInnerScreenY):void 0!=g.screenX&&null!=g.screenX?0!=g.screenLeft+8&&g.screenLeft+8!=screen.width||0!=g.screenTop+8&&g.screenTop+8!=screen.height?(f=g.screenLeft,b=g.screenTop+(g.outerHeight-g.innerHeight)):(f=g.screenLeft+8,b=g.screenTop+(g.outerHeight-g.innerHeight)+8):(f=g.screenLeft,b=g.screenTop);var a={D:null,C:null,I:null,J:null,i:!1},c=this.b.ya(g);a.D=g.innerWidth||
c.clientWidth;a.C=g.innerHeight||c.clientHeight;a.I=f;a.J=b;a.i=!0;return a};return this.na(a)};this.ma=function(a,d){c=1;this.R==this.V.CrossDomain?this.b.ua(this.window)&&this.window.$sf.ext.geom&&this.b.Ka(this.window).par?(c=8,this.ma=function(){var a=this.b.Ka(this.window),g=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(a.win.h):this.N.Explorer.W,b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};
b.v=parseInt(a.self.l)-parseInt(a.par.l);b.u=parseInt(a.self.t)-parseInt(a.par.t);b.K=parseInt(a.self.l);b.L=parseInt(a.self.t);b.G=parseInt(a.win.l)+b.v;b.H=parseInt(a.win.t)+b.u+g;b.o=parseInt(a.self.w);b.m=parseInt(a.self.h);b.i=!0;b.rect={top:b.u,bottom:b.u+b.m,left:b.v,right:b.v+b.o};return b}):this.M.X==this.Y.Firefox?this.ma=function(){var a=1;window.devicePixelRatio&&(a=window.devicePixelRatio);var g=this.window.screenX,b=this.window.screenY,c=this.window.mozInnerScreenX/a-g,a=this.window.mozInnerScreenY/
a-b-this.N.Firefox.W,c={left:c,top:a,right:c+this.window.innerWidth,bottom:a+this.window.innerHeight},a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};a.v=c.left;a.u=c.top;a.K=null;a.L=null;a.G=g+c.left;a.H=b+c.top;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.i=!0;a.rect=c;this.b.Eb()&&(a=this.kb(a));return a}:this.b.jc(this.window)?(c=32,this.ma=function(){var a={v:null,u:null,o:null,m:null,i:!1,rect:null,O:null,oa:null,K:null,L:null,G:null,H:null};
null!=this.pa?(a.v=this.pa.boundingClientRect.left,a.u=this.pa.boundingClientRect.top,a.o=this.pa.boundingClientRect.width,a.m=this.pa.boundingClientRect.height):(a.v=0,a.u=0,a.o=0,a.m=0);a.i=!0;a.rect={top:a.u,bottom:a.u+a.m,left:a.v,right:a.v+a.o};return a}):this.M.X==this.Y.IE&&/^[11|12]/.test(this.M.ta)?this.ma=function(a){var g=this.window.screenLeft-window.screenX,b=this.window.screenTop-window.screenY-this.N.Explorer.W,g={left:g,top:b,right:g+this.window.innerWidth,bottom:b+this.window.innerHeight},
b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};b.v=g.left;b.u=g.top;b.K=null;b.L=null;b.G=a.I+g.left;b.H=a.J+g.top;b.o=this.window.innerWidth;b.m=this.window.innerHeight;b.i=!0;b.rect=g;this.b.Eb()&&(b=this.kb(b));return b}:this.M.X==this.Y.IE&&/[6-9]|[10]/.test(this.M.ta)?this.ma=function(){if(8==document.documentMode)return{v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};var a=this.window.Ra&&this.window.qa?this.window.Ra.Pb-
this.window.qa.Pb:0,g=this.window.Ra&&this.window.qa?this.window.Ra.Ob-this.window.qa.Ob:0,b=this.b.ya(this.window),c={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};c.v=g;c.u=a;c.K=null;c.L=null;c.G=this.window.qa?g+this.window.qa.Fa:null;c.H=this.window.qa?a+this.window.qa.Ga:null;c.o=this.window.innerWidth||b.clientWidth;c.m=this.window.innerHeight||b.clientHeight;c.i=!0;c.rect={left:g,top:a,right:g+(this.window.innerWidth||b.clientWidth),bottom:a+(this.window.innerHeight||
b.clientHeight)};this.b.Eb()&&(c=this.kb(c));return c}:this.b.tb()?(c=512,this.ma=function(){var a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};null!=this.c&&(adData=this.b.mb(this.c),a.o=adData?adData.w:this.window.innerWidth,a.m=adData?adData.h:this.window.innerHeight);return a}):this.ma=this.M.X==this.Y.Chrome?function(){var a=null,g=null,b=!1;try{var c=this.window.frameElement.offsetTop,a=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,
g=c-this.window.frameElement.offsetParent.scrollTop,b=!0}catch(k){}c={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};c.v=a;c.u=g;c.K=null;c.L=null;c.G=null;c.H=null;c.o=this.window.innerWidth;c.m=this.window.innerHeight;c.i=b;c.rect=b?{left:a,top:g,right:a+this.window.innerWidth,bottom:g+this.window.innerHeight}:null;this.b.Eb()&&(c=this.kb(c));return c}:null!=this.fa&&this.fa.Va()?function(){var a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,
rect:null,O:null,oa:null};null!=this.c&&(adData=this.b.mb(this.c),a.o=adData?adData.w:this.window.innerWidth,a.m=adData?adData.h:this.window.innerHeight);return a}:function(){return{v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null}}:this.ma=function(a){var g=this.Yb(this.c,this.window),b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null},c=this.b.ac(this.c,this.window),k=this.b.uc(this.c,this.window);b.v=k.left;b.u=k.top;b.K=
g.x;b.L=g.y;b.G=a.I+k.left;b.H=a.J+k.top;b.o=k.w;b.m=k.h;b.i=!0;b.rect=c;b.O=k;return b};return this.ma(a,d)};this.kb=function(a){if(this.window.document.body==this.c||this.window.document.documentElement==this.c)return a;var c=this.b.mb(this.c);if(c){var d=c.w,g=c.h,b=a.v,e=a.u,v=a.H,f=a.G;null!=a.v&&null!=a.u&&null!=a.m&&null!=a.o&&a.rect&&(0<c.t?(e=a.u+c.t,null!=a.H&&(v=a.H+c.t)):g+=c.t,0<c.l?(b+=c.l,null!=a.G&&(f=a.G+c.l)):d+=c.l,c.r>a.o&&(d-=c.r-a.o),c.Cc>a.m&&(g-=c.Cc-a.m),a.o=0<d?d:0,a.m=0<
g?g:0,a.v=b,a.u=e,a.H=v,a.G=f,a.rect.left=a.v,a.rect.top=a.u,a.rect.right=a.v+c.w,a.rect.bottom=a.u+c.h,a.O={w:d,h:g,left:b,right:b+d,top:e,bottom:e+g})}return a};this.De=function(){var a=screen.availWidth,c=screen.availHeight,d=screen.width,g=screen.height,b=0,e=0;this.Sc&&(e=this.window.top,b=e.screenX,e=e.screenY);return{i:this.N.Ua?!1:"undefined"!==typeof b,zb:a||d,yb:c||g,Qf:b,Rf:e,Aa:b-(d-a),rf:e-(g-c)}};this.me=function(){var a=this.De(),c=this.na(a),d=this.ma(c,a);return{da:c,g:d,va:a,Fb:(null==
c.I||null==c.J?0:this.ha.Nd)|(null==c.D||null==c.C?0:this.ha.Od)|(null==d.v||null==d.u?0:this.ha.Id)|(null==d.K||null==d.L?0:this.ha.Kb)|(null==d.G||null==d.H?0:this.ha.Hd)|(null==d.m||null==d.o?0:this.ha.Lb)|(null==a.yb||null==a.zb?0:this.ha.Md),P:this.Hc(d.m,d.o)}};this.Hc=function(a,c){null==a&&(a=0);null==c&&(c=0);return 1!=this.N.Ua?242500<=a*c:!1};this.ue=function(){this.b.a("c10");if(null!=this.c)if(this.b.Xc(this.c,this.window))try{var a={timeStamp:new Date,j:-3,ia:-3,s:null,P:!1,ea:0};if(!this.ec())return a;
var d=this.me(),e;if(!d.g.i||!d.da.i){if(this.b.ua(this.window)&&this.window.$sf.ext.inViewPercentage)return e=this.window.$sf.ext.inViewPercentage(),{timeStamp:new Date,j:e,ia:e,s:d,P:d.P,ea:16};if(this.b.tb()&&this.rb)return e=0,null!=this.qb&&(e=Math.round(100*this.qb.intersectionRatio)),{timeStamp:new Date,j:e,ia:e,s:d,P:this.Hc(d.g.m,d.g.o),ea:512};if(this.fa.Va()){var g={timeStamp:new Date,j:-3,ia:-3,s:null,P:!1,ea:2};if(0==this.fa.Re())g.j=-6,g.ia=-6,this.fa.sd(this.window,this.c);else{var b=
this.fa.He();null!=b&&(g.s=d,g.P=d.P,g.j=b,g.ia=b)}return g}a.s=d;c&&(a.ea=c);return a}if(d.g&&d.g.O&&(0===d.g.O.w||1===d.g.O.w||0===d.g.O.h||1===d.g.O.h))return{timeStamp:new Date,j:-5,ia:-5,s:d,ea:c};e=d.g.O?this.Zb(d.va,d.g.O,d.da,d.g.rect):this.Zb(d.va,d.g.rect,d.da);return{timeStamp:new Date,j:e,ia:e,s:d,P:d.P,ea:c}}catch(t){return{timeStamp:new Date,j:-4,ia:-4,s:null,P:!1,ea:c}}else return{timeStamp:new Date,j:-2,ia:-2,s:null,P:!1,ea:0};else return{timeStamp:new Date,j:-1,ia:-1,s:null,P:!1,
ea:0}};this.ne=function(a,c){this.b.a("c11");var d=null,g=null;if(null!=a.s){var b=a.s.g;c<=this.N.cf&&(d=0<=a.j||-5==a.j?a.P&&a.j>=this.N.Wa||0==a.P&&50<=a.j?!0:!1:null,g=a.P?this.N.Wa/100:.5,g=0==d?0>b.u+b.m*g?!0:!1:1==d?!1:null)}return{Uc:g,Vc:d}};this.sb=function(a){this.b.a("c12");var c=null;if(2!=a.ea&&512!=a.ea&&null!=a.s){var d=a.s.Fb,g=a.s.g;(d&this.ha.Kb)==this.ha.Kb&&(d&this.ha.Lb)==this.ha.Lb&&(c=this.Zb(a.s.va,{left:g.K,top:g.L,right:g.K+g.o,bottom:g.L+g.m},a.s.da,g.rect),c=0<=a.j?a.P&&
c>=this.N.Wa||0==a.P&&50<=c?!1:!0:null)}this.b.a("c12e");return c};this.hd=function(){function a(c){c.forEach(function(a){d.qb=a})}var d=this;"undefined"!=typeof IntersectionObserver&&null!=this.c&&(c=512,this.wb=new IntersectionObserver(a,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.wb.observe(this.c),this.rb=!0)};this.Je=function(){this.c=null;null!=this.wb&&(this.wb.disconnect(),this.qb=null,this.rb=!1)}}
function P(){this.getElementVolume_object=function(a){var d=a.getAttribute("width"),e=a.getAttribute("height");null==d||""==d||null==e||""==e?(a=a.parentNode,a={w:a.clientWidth,h:a.clientHeight}):a={w:d,h:e};return a};this.Se=function(a){var d=0;try{for(;null!=a&&10>d;){if("none"==window.getComputedStyle(a).display||"hidden"==window.getComputedStyle(a).visibility)return!1;a=a.parentElement;d++}}catch(e){}return!0};this.ba=function(a,d){this.a("cm1");var e=null,h=a.nodeName.toLowerCase();d&&this["getElementVolume_"+
h]&&(e=this["getElementVolume_"+h](a));if(!e&&(e=this.mb(a),this.a("cm2e"),!e||1>=e.w||1>=e.h))return this.a("cm1e"),{w:0,h:0};e.w.indexOf&&e.w.indexOf("px")&&(e.w=e.w.replace("px",""));e.h.indexOf&&e.h.indexOf("px")&&(e.h=e.h.replace("px",""));this.a("cm1e");return e};this.mb=function(a){this.a("cm2");try{var d;return document.body.getBoundingClientRect&&(d=a.getBoundingClientRect())?{w:d.right-d.left,h:d.bottom-d.top,l:d.left,t:d.top,Cc:d.bottom,r:d.right}:null}catch(e){return null}};this.ya=function(a){return a.document.documentElement.clientHeight?
a.document.documentElement:a.document.body};this.Nc=function(a,d){this.a("ff9");var e=0,h=!1;if(a.document.all)for(var l=0;l<a.document.all.length;l++)"BODY"==a.document.all[l].nodeName&&(h=!0),h&&("width"==d?a.document.all[l].width>e&&(e=a.document.all[l].width):a.document.all[l].height>e&&(e=a.document.all[l].height));this.a("ff9e");return e};this.$c=function(a,d){for(var e=this.ya(a),h=a.innerWidth||e.clientWidth||this.Nc(a,"width"),e=a.innerHeight||e.clientHeight||this.Nc(a,"height"),l=d.length,
m=0,q=0;q<l;q++)if(15>=Math.abs(h-d[q].w)){m=d[q].h.length;for(h=0;h<m;h++)if(15>=Math.abs(e-d[q].h[h]))return!0;break}return!1};this.Ef=function(a){for(var d=[],e=-1;d[++e]=a[e];);d.length--;return d};this.Hb=function(a,d,e,h){var l=a.getElementsByTagName("*"),l=this.Ef(l);l.unshift(a);for(var m=["EMBED","IFRAME","OBJECT","IMG","DIV"],q=[],p=0;p<l.length;p++){var c=l[p];if(-1!=m.indexOf(c.nodeName)){var k=h(c);k&&q.push({Bc:k.w*k.h,w:k.w,h:k.h,type:c.nodeName||"other",ie:c})}}q=q.sort(function(a,
c){return c.Bc-a.Bc||m.indexOf(c.type)-m.indexOf(a.type)});(d=0<q.length&&q[0].w>d&&q[0].h>e?q[0].ie:null)&&a&&(d.pb=a.pb);return d};this.Xc=function(a,d){this.a("ff10");try{if(!a)return!1;for(d||(d=window);a!=d.document&&a.parentNode;)a=a.parentNode;this.a("ff10e");return a==d.document}catch(e){return!1}};this.ac=function(a,d){var e=d.parent,h={left:0,right:0,top:0,bottom:0};if(a){var l=a.getBoundingClientRect();d!=e&&this.Mb(d,e)&&(h=this.ac(d.frameElement,e));h={left:l.left+h.left,right:l.right+
h.left,top:l.top+h.top,bottom:l.bottom+h.top}}return h};this.Mb=function(a,d){var e=!1;if(a==d)e=!0;else try{a.document.domain==d.document.domain&&(e=!0)}catch(h){}return e};this.ve=function(a){if(a)try{if(a.contentDocument&&this.Wc(a.contentDocument))return a.contentDocument;if(a.contentWindow&&this.vb(a.contentWindow))return a.contentWindow.document}catch(d){}return null};this.Rc=function(a){return a?a.defaultView||a.parentWindow:null};this.Me=function(a,d){return-1<d.indexOf(a)};this.pe=function(a){try{return a!=
a.top&&a.parent&&this.vb(a.parent)?a.parent:null}catch(d){return null}};this.vb=function(a){try{return a&&a.document&&this.Wc(a.document)?!0:!1}catch(d){return!1}};this.Wc=function(a){try{return a&&a.getElementsByTagName&&a.getElementById?!0:!1}catch(d){return!1}};this.uc=function(a,d){var e=d.parent,h={w:0,h:0,left:0,right:0,top:0,bottom:0};a&&(h=this.ac(a,d),h.w=h.right-h.left,h.h=h.bottom-h.top,d!=e&&this.Mb(d,e)&&(e=this.uc(d.frameElement,e),e.bottom<h.bottom&&(e.bottom<h.top&&(h.top=e.bottom),
h.bottom=e.bottom),e.top>h.top&&(e.top>h.bottom&&(h.bottom=e.top),h.top=e.top),e.right<h.right&&(e.right<h.left&&(h.left=e.right),h.right=e.right),e.left>h.left&&(e.left>h.right&&(h.right=e.left),h.left=e.left),h.w=h.right-h.left,h.h=h.bottom-h.top));return h};this.Sb=function(a,d){return function(){return a.apply(d,arguments)}};this.ra=function(a){try{return a?a.length?a.length:0:0}catch(d){return 0}};this.cc=function(a){for(var d=[],e=0;e<a.length;e++)this.Se(a[e])&&d.push(a[e]);return d};this.a=
function(a){try{maxLength=3,$dv&&($dv.La=$dv.La||[],$dv.La.push(a),$dv.La.length>maxLength&&$dv.La.shift())}catch(d){}};this.ye=function(){try{return $dv&&$dv.La?$dv.La.join():""}catch(a){return""}};this.ua=function(a){if(a.$sf&&a.$sf.ext)if(a.$sf.ext.geom){if(a=this.Ka(a),null!=a&&a.win&&(0<a.win.h||0<a.win.w))return this.ua=function(){return!0},!0}else if(a.$sf.ext.inViewPercentage)return!0;this.ua=function(){return!1};return!1};this.Ka=function(a){a.$sf.ext.geom&&(this.Ka="function"==typeof a.$sf.ext.geom?
function(a){return a.$sf.ext.geom()}:function(a){return a.$sf.ext.geom});return this.Ka(a)};this.F=function(a,d){if(null!=a&&null!=d)for(var e in d)d.hasOwnProperty(e)&&(a[e]=d[e])};this.jc=function(a){return a.context&&a.context.observeIntersection?!0:!1};this.tb=function(){var a=!1;if(1==this.lb("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(a=!0);return a};this.ub=function(a,d,e){var h=e&&e.Enums.BrowserId||window.$dv.Enums.BrowserId;if(a==(e&&e.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&
d.X===h.Safari&&(null===d.ta||void 0===d.ta||!/^[3-8]/.test(d.ta)))return this.ub=function(){return!0},!0;this.ub=function(){return!1};return!1};this.lb=function(a){var d,e=this.Lc();e&&e.AVO&&(d=e.AVO[a]);return d};this.Lc=function(){var a={},d=window.$dv,e=window.$uid;d.tags&&d.tags[e]&&(a=d.tags[e]);return a};this.Eb=function(){return 1==this.lb("sam")?!0:!1};this.Ta=function(a){return a.document.hasFocus()};this.Ja=new function(){var a=this;a.cache=[];window.addEventListener?a.add=function(d,
e,h,l,m){if("undefined"==typeof l||null==l)l=window;l.addEventListener(d,e,h);m&&a.cache.push([d,e,h,l])}:window.attachEvent?a.add=function(d,e,h,l,m){if("undefined"==typeof l||null==l)l=window;l["e"+d+e]=e;l[d+e]=function(){l["e"+d+e](window.event)};l.attachEvent("on"+d,l[d+e]);m&&a.cache.push([d,e,h,l])}:a.add=function(){};window.removeEventListener?a.remove=function(a,e,h,l){if("undefined"==typeof l||null==l)l=window;l.removeEventListener(a,e,h)}:window.detachEvent?a.remove=function(a,e,h,l){if("undefined"==
typeof l||null==l)l=window;l.detachEvent("on"+a,l[a+e]);l[a+e]=null;l["e"+a+e]=null}:a.remove=function(){};a.flush=function(){for(var d=0;d<a.cache.length;d++)a.remove.apply(a,a.cache[d]);a.cache=[]}};this.getElementsByClassName=function(a,d){return a.getElementsByClassName?a.getElementsByClassName(d):a.querySelectorAll?a.querySelectorAll("."+d):[]};this.Ua=function(){var a=!1;if($dv&&$dv.CommonData){var d=$dv.CommonData.detectedDeliveryType;d&&0!=d?a=2==d||3==d:(d=$dv.CommonData.deviceType)&&(a=
2==d||3==d)}return a};this.xe=function(a,d){var e=a||"",h="";if(d&&(e+=": "+(d.message||""),d.stack)){var h=d.stack||"",l=h.indexOf("at ");0>l&&(l=0);h=", Stack: "+h.slice(l,h.length)}e=e.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");h=h.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");l=null;try{l=encodeURIComponent(e+h).slice(0,500)}catch(m){try{l=encodeURIComponent(e).slice(0,500)}catch(q){l=
e.slice(0,500)}}return l}}
function X(a,d,e,h,l,m){var q=new P;this.f=h;this.window=e;this.c=null;this.dataObj=a;this.dvObj=a.dvObj||window.$dv;this.hc=null;this.M={X:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Y=this.dvObj.Enums.BrowserId;this.R=l;this.V=this.dvObj.Enums.TrafficScenario;this.ja=d;this.A=m.A;115==this.dataObj.cb&&(this.A.B.h=20,this.A.B.w=20);this.pf=function(){m.gf(this.c);this.c=null};var p=[],c=["object","embed","img","iframe"];this.dataObj.spotXmode&&(c=["object","embed",
"video","iframe"]);this.Pe=function(a){q.a("a33");a=q.ba(a);return this.Qe(a)};this.Qe=function(a){if(a){var c=a.w;a=a.h;for(var e=d.length,g=0,b=0;b<e;b++)if(15>=Math.abs(c-d[b].w))for(var g=d[b].h.length,t=0;t<g;t++)if(15>=Math.abs(a-d[b].h[t]))return!0}return!1};this.se=function(){q.a("a34");return this.te()||this.sf()};this.sf=function(){q.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),c=[],d=window.parent;q.a("ff6");try{c=d.document.getElementsByTagName("script")}catch(b){}q.a("ff6e");
for(var d=c.length,g=0;g<d;g++)if(c[g]&&c[g].id&&c[g].id.substr(7)==a)return c[g];return null};this.te=function(){q.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.Ud=function(a){q.a("a38");var d={node:a,xa:0};a=[];for(p=[];d||0<a.length;){try{var e;if(!(e=1==d.xa&&m.kc(d.node)&&!m.ka(d.node)&&m.S(d.node))){var g;a:{var b=d.node;try{if(b&&-1!=c.indexOf(b.nodeName.toLowerCase())){g=
!0;break a}}catch(h){}g=!1}e=g&&this.Pe(d.node)&&!m.ka(d.node)&&m.S(d.node)}if(e)return d;if(d.xa<=this.A.Ze){var t,v=d.node,f=d.xa,d=[],u=v.parentNode;u&&-1==p.indexOf(u)&&(p.push(u),d.push({node:u,xa:f+1}));if(v.hasChildNodes())for(var n=0;n<v.childNodes.length;n++)v.childNodes[n]&&-1==p.indexOf(v.childNodes[n])&&1===v.childNodes[n].nodeType&&(p.push(v.childNodes[n]),d.push({node:v.childNodes[n],xa:f+1}));var x,l=v,A=[],y=null;l&&l.parentNode&&(y=l.parentNode.firstChild);for(;y;)1===y.nodeType&&
y!==l&&A.push(y),y=y.nextElementSibling||y.nextSibling;x=A;for(n=0;n<x.length;n++)x[n]&&-1==p.indexOf(x[n])&&1===x[n].nodeType&&(p.push(x[n]),d.push({node:x[n],xa:f+1}));if(t=d)for(d=0;d<t.length;d++)a.push(t[d])}}catch(h){}d=a.shift()}return{node:null}};this.Ae=function(){q.a("a37");var a=this.se(),c=null;a&&(c=this.Ud(a));return c};this.ke=function(a){q.a("a31");if(this.c=m.ze())return this.f.yd(),this.hc=!0,this.c;if(this.dataObj.btreg&&!0===this.hc&&1<a)return this.c;"1"!=this.dataObj.displaynon&&
(a=this.Ae())&&a.node&&(this.f.xd(a.xa),this.c=a.node);return this.c};return this}
function aa(a,d,e,h,l,m){function q(a,b){for(var c=[],d=0;d<r.length;d++){var f=[],f=b(a,r[d]),e=k.ra(f);if(0!=e){var n=k.Rc(r[d]);if(null!=n)for(var h=0;h<e;h++)try{f[h].pb=n,c.push(f[h])}catch(p){}}}return c}function p(a,b){return q(a,function(a,g){k.a("ff4");var f=g.getElementsByTagName(a);k.a("ff4e");return"1"!=b?f:k.cc(f)})}var c=this,k=new P,w="Microsoft Internet Explorer"==navigator.appName;this.dataObj=a;this.window=d;this.c=e;this.R=h;this.V=l;this.dvObj=void 0===m?m={}:m;this.A={B:{h:1,
w:1},If:{h:10,w:10},Ze:10};115==this.dataObj.cb&&(this.A.B.h=20,this.A.B.w=20);this.Ce=function(a){if(a.scanOrder)return a.scanOrder;var b=[1==w?"object":"embed",1==w?"embed":"object","href","img","span","iframe","frameElement","div"];a.findclass&&1==a.findclass&&b.push("classDeclaration");a.gb&&0<a.gb.length&&b.unshift("searchCustomElementsFromTag");return b};this.searchCustomElementsFromTag=function(a){for(var b=0;b<a.gb.length&&(c.Ic(a.gb[b],a),!c.c);b++);};this.Gb=[["DCF",'"'],[";",";"],["%3B",
"%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.ce=function(){var g=c.dataObj.jb+"-"+c.dataObj.ib;a.isBrandShieldOrigin&&(g+="-bs");return g.replace(RegExp(",","g"),";")};this.qc=this.ce();this.Ic=function(a,b){if(b.btreg)for(var d=p(a,b.displaynon),e=k.ra(d),f=0;f<e;f++)if(d[f]&&c.wa(b,d[f],!0)&&!c.ka(d[f])){var u=this.kc(d[f]);if(u&&(n=k.ba(u))&&n.h>c.A.B.h&&n.w>c.A.B.w&&c.S(u)){c.c=u;c.S(d[f]);break}var n=k.ba(d[f]);if(n&&n.h>c.A.B.h&&
n.w>c.A.B.w&&c.S(d[f])){c.c=d[f];break}if((u=k.Hb(d[f],c.A.B.w,c.A.B.h,k.Sb(k.ba,k)))&&c.S(u)){c.c=u;c.S(d[f]);break}}};this.div=function(a){this.Ic("div",a)};this.span=function(a){k.a("a10");if(a.btreg)for(var b=p("span",a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e],!0)&&!c.ka(b[e])){var f=b[e];k.a("a20");if(f&&"1"==f.getAttribute("adunit")){c.c=b[e];break}if(f=this.kc(b[e])){var u=k.ba(f);if(u&&u.h>c.A.B.h&&u.w>c.A.B.w&&c.S(f)){c.c=f;c.S(b[e]);break}}if((f=k.Hb(b[e],c.A.B.w,c.A.B.h,k.Sb(k.ba,
k)))&&c.S(f)){c.c=f;c.S(b[e]);break}}};this.object=function(a){k.a("a11");for(var b=p("object",a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e])&&!c.ka(b[e])){var f=k.Hb(b[e],c.A.B.w,c.A.B.h,k.Sb(k.ba,k));if(f&&c.S(f)){c.S(b[e]);c.c=f;break}}};this.embed=function(a){k.a("a12");for(var b=p("embed",a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e])&&!c.ka(b[e])){var f=k.ba(b[e]);if(f&&f.h>c.A.B.h&&f.w>c.A.B.w&&c.S(b[e])){c.c=b[e];break}}};this.href=function(a){k.a("a13");for(var b=p("a",
a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e])&&!c.ka(b[e])){var f=b[e].getElementsByTagName("img");if(0<f.length){var u=k.ba(f[0]);if(u&&u.h>c.A.B.h&&u.w>c.A.B.w&&c.S(b[e])){c.c=f[0];break}}}};this.img=function(a){k.a("a14");for(var b=p("img",a.displaynon),d=k.ra(b),e=0;e<d;e++)if(b[e]&&c.wa(a,b[e])&&0>b[e].src.indexOf("event")&&!c.ka(b[e])){var f=k.ba(b[e]);if(f&&f.h>c.A.B.h&&f.w>c.A.B.w&&c.S(b[e])){c.c=b[e];break}}};this.classDeclaration=function(a){k.a("a9");var b="undefined"!==typeof window.document.getElementsByClassName,
d="undefined"!==typeof window.document.querySelectorAll;if(a.btreg){var e=[];if(b)e=c.getElementsByClassName(a.btreg,a.displaynon);else if(d)e=c.querySelectorAll(a.btreg,a.displaynon);else return;a=k.ra(e);for(b=0;b<a;b++)if(e[b]&&!c.ka(e[b])&&(d=k.ba(e[b]))&&d.h>c.A.B.h&&d.w>c.A.B.w&&c.S(e[b])){c.c=e[b];break}}};this.iframe=function(a){k.a("a15");for(var b=p("iframe",a.displaynon),d=k.ra(b),e=0;e<d&&!c.xc(a,b[e]);e++);};this.frameElement=function(a){try{k.a("a16"),h==l.SameDomain&&c.xc(a,window.frameElement)}catch(b){}};
this.getElementsByClassName=function(a,b){return q(a,function(a,c){k.a("ff1");var f=c.getElementsByClassName(a);k.a("ff1e");return"1"!=b?f:k.cc(f)})};this.querySelectorAll=function(a,b){return q(a,function(a,c){k.a("ff3");var f=c.querySelectorAll("."+a);k.a("ff3e");return"1"!=b?f:k.cc(f)})};this.la=function(a,b){k.a("a28");return!a||!b||5>b.length?!1:null!=(c.vc?c.vc(a,b):c.Ib(a,b))?!0:c.Tb&&"function"===typeof c.Tb?c.Tb(a,b):!1};this.wa=function(a,b,d){k.a("a22");var e=null;return a.btreg&&(c.vc=
1==a.Te?c.Ed:c.Ib,e=c.Kd(a,b,d))||!c.c&&(e=c.Ld(a,b))?!0:!1};this.Pd=function(a){k.a("a21");if(a&&!c.ka(a)){var b=k.ba(a);if(b&&b.h>c.A.B.h&&b.w>c.A.B.w&&c.S(a))return c.c=a,!0}return!1};this.xc=function(a,b){k.a("a17");return c.wa(a,b)?c.Pd(b):!1};this.ka=function(a){k.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var b=0;b<a.length;b++)if(a[b]==c.qc)return!0}return!1};this.S=function(a){k.a("a18");if(a&&0==c.ka(a))try{var b=a.getAttribute("dvvisit");b?a.setAttribute("dvvisit",
b+","+c.qc):(k.a("ff5"),b=window.document.createAttribute("dvvisit"),k.a("ff5e"),b.value=c.qc,a.setAttributeNode(b));$dv.eventBus&&window&&$dv.eventBus.dispatchEvent(window,"adLocated",{adElement:a,timeStamp:(new Date).getTime()});return!0}catch(d){}return!1};this.gf=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.Ed=function(a,b){k.a("a29");var d;try{d=(new RegExp(b)).exec(a)}catch(e){d=c.Ib(a,b)}return d};this.Ib=function(a,b){k.a("a30");var c=null;-1!==
a.indexOf(b)&&(c=a);return c};this.kc=function(a){var b=null;"celtra-ad-v3"==a.className&&a.celtra&&1==a.celtra.loaded&&(b=a.celtra.viewabilityObservee);b&&(b.pb=k.Rc(b.ownerDocument)||window);return b};var r=[];this.Kd=function(a,b,d){k.a("a23");var e;try{if(a.Fc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(e=c.la(b.id,a.btreg))||(e=c.la(b.src,a.btreg));e||(e=c.la(b.href,a.btreg));e||(e=c.la(b.getAttribute("flashvars"),a.btreg));e||(e=c.la(b.name,a.btreg));!e&&a.findclass&&1==a.findclass&&
(e=c.la(b.getAttribute("class"),a.btreg));if(!e&&c.dataObj.Ia&&0<c.dataObj.Ia.length)for(var f=c.dataObj.Ia,u=0;u<f.length&&!(e=c.la(b.getAttribute(f[u]),a.btreg));u++);e||d||(e=c.la(b.innerHTML,a.btreg));e&&!d&&(e=c.Jd(a,b));return e}catch(n){return e}};this.Da=function(a,b){k.a("a25");if(!a)return!1;a=a.toLowerCase();for(var d=0;d<c.Gb.length;d++){var e;if(b.Ac&&(e=(c.Gb[d][0]+b.Ac).toLowerCase(),e=a.indexOf(e),-1<e)||b.ed&&(e=(c.Gb[d][0]+b.ed).toLowerCase(),e=a.indexOf(e),-1<e))return!0}return!1};
this.Ld=function(a,b){k.a("a24");var d;try{if(a.Fc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(d=c.Da(b.id,a))||(d=c.Da(b.src,a));d||(d=c.Da(b.href,a));d||(d=c.Da(b.Nf,a));d||(d=c.Da(b.name,a));d||(d=c.Da(b.innerHTML,a));if(!d&&c.dataObj.Ia&&0<c.dataObj.Ia.length)for(var e=c.dataObj.Ia,f=0;f<e.length&&!(d=c.la(b.getAttribute(e[f]),a.btreg));f++);return d}catch(u){return d}};this.Jd=function(a,b){k.a("a26");return null==a.Qa||""==a.Qa?!1:c.la(c.Dd(b),a.Qa)};this.searchByAdSrvId_8=function(a,
b){k.a("a1");var c=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=c&&(c=c.toString(),c.replace(RegExp("-","g"),"")==b)?!0:!1};this.Tb=this["searchByAdSrvId_"+(c.dataObj?c.dataObj.cb||"":"")];this.Dd=function(a){k.a("a27");if(a.outerHTML)return a.outerHTML;for(var b=a.attributes.length,c="",d=0;d<b;d++)c=c+a.attributes[d].nodeName+"="+a.attributes[d].nodeValue+" ";return c+a.innerHTML};this.ze=function(){k.a("32");var a=[];void 0===m.tags&&(m.tags={});void 0===m.tags[$uid]&&(m.tags[$uid]={});void 0!==
m.tags[$uid].spvi&&(a.push(m.tags[$uid].spvi),-1<a[0].scanOrder.indexOf(",")&&(a[0].scanOrder=a[0].scanOrder.split(",")));c.dataObj.scanOrder=this.Ce(c.dataObj);a.push(c.dataObj);var b=c.window,d=0,h=[];try{do{h.push(b.document);for(var f=h,u=b.document.getElementsByTagName("iframe")||[],n=0;n<u.length||25>n;n++){var p=null,p=k.ve(u[n]);void 0!==p&&null!==p&&0==k.Me(p,f)&&f.push(p)}b=k.pe(b)}while(b&&10>++d)}catch(l){}r=h;for(b=0;b<a.length;b++)for(d=a[b],h=0;h<d.scanOrder.length;h++)if(void 0!=c[d.scanOrder[h]]&&
(c[d.scanOrder[h]](d),c.c))return $dv&&$dv.eventBus&&$dv.eventBus.dispatchEvent&&$dv.eventBus.dispatchEvent(window,"avsAdFound",{timeStamp:(new Date).getTime(),adDomElement:c.c}),c.c;return e};return this}
function dv_CustomClientViewAssureService(a){function d(a){return{nf:{adView:a.rq.av,Le:a.rq.ic,yc:a.rq.adc,Ye:a.rq.mla,bd:a.rq.ldav,focus:a.rq.fc,zc:a.rq.as},mf:{dd:e(a.rp.mt),ff:e(a.rp.pt),$e:e(a.rp.mr),ef:e(a.rp.pr),eventId:a.rp.eid,Ec:a.rp.bl}}}function e(a){return"string"==typeof a?Array(a):a}this.Td=dv_InViewService;this.Td(a);this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this.b=new P;this.$a=[];a=$dv.tags[$uid].dc||a.dc||[];var h=this.b.Lc().bgm,l;for(l in a)a.hasOwnProperty(l)&&
this.$a.push(new window.Xb.de(d(a[l]),h));var m=this.Jb;this.Jb=function(a){a=m(a);for(var c=0;c<this.$a.length;c++)this.$a[c].fe(a,this.Z.interval);return a};var q=this.Oa;this.Oa=function(a,c){var d={};q(a,c);if(1==this.Ub){for(var e=0;e<this.$a.length;e++){var h=this.$a[e].bf(),g;for(g in h)h.hasOwnProperty(g)&&(d[g]=h[g])}$dv.registerEventCall($uid,d)}}}window.Xb=window.Xb||{};
window.Xb.de=function(a,d){function e(a){a.s&&a.s.g&&a.s.g.m&&a.s.g.o&&242500<=a.s.g.o*a.s.g.m&&(m=!0,h.bd&&(h.adView=h.bd),e=function(){})}var h=a.nf,l=a.mf,m=!1;this.fe=function(a,d){e(a);var l=!0,m;m=h.focus?a.j:a.ia;h.adView&&h.adView>m&&(l=!1);h.zc&&a.s&&a.s.g&&a.s.g.m&&a.s.g.o&&a.s.g.o*a.s.g.m<h.zc&&(l=!1);l?q+=d:h.Le&&(q=0);this.Yd(a)};var q=0;this.bf=function(){return this.jf(l.dd,l.$e,l.Ec)};this.jd=function(){this.kf(l.dd,l.ff,l.ef,l.Ec,l.eventId);this.jd=function(){}};this.Yd=function(a){(h.yc&&
q>=h.yc||m&&h.Ye)&&this.jd(a)};var p;this.jf=function(a,e,h){var l={};if(d&&h)return l;if(a)for(p=$dv.tags[$uid].getTimeDiff(),h=0;h<a.length;h++)l[a[h]]=p;if(e)for(h=0;h<e.length;h++)$dv.pubSub.publish(e[h],$uid),window&&$dv.pubSub.publish(e[h],window.$frmId);return l};this.kf=function(a,e,h,l,g){if(!d||!l){if(e){l={};for(var b=$dv.tags[$uid].getTimeDiff(),m=0;m<e.length;m++)l[e[m]]=b;g&&(l.evid=g);if(a)for(m=0;m<a.length;m++)l[a[m]]=p||$dv.tags[$uid].getTimeDiff();$dv.registerEventCall($uid,l)}if(h)for(m=
0;m<h.length;m++)$dv.pubSub.publish(h[m],$uid),window&&$dv.pubSub.publish(h[m],window.$frmId)}}};
function dv_InViewService(a){function d(){null===m.interval&&(m.interval=setInterval(m.we(),m.Z.interval))}function e(){if(!1===m.Zc){m.Zc=!0;try{m.b.Ja.remove("load",arguments.callee,!1,element)}catch(a){}m.Ab();m.b.a("s41");m.sa=new W(m.Xd?m.Xd:m.window,m.c,m.R,m.M,m.N,m.f.Gc,m.dvObj,m.impressionId);m.b.a("s42");m.Gd();m.start()}}function h(a,b){return a.isReportingDisabled?new S:new R(a,b)}function l(a,b){m.b.Ja.add("click",function(){m.Nb(!0);$dv.registerEventCall(m.impressionId,"ad"==b?{dvp_csad:1}:
{dvp_csifr:1});m.b.Ja.remove("click",arguments.callee,!1,a)},!1,a,!1)}var m=this;this.cd=10;this.Sd=a.serverSettings&&a.serverSettings.jsVersion?a.serverSettings.jsVersion:"676";this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this._minor_version="0";this.b=new P;this.Ie=function(){for(var a=document.getElementsByTagName("script"),b=a.length,d,c=0;c<b;c++)if(d=a[c].src,/visit[.]js/.test(d))return d.substring(d.indexOf("?")+1)};var q=this.Zc=!1,p=!1;this.Fe=function(){var a=
"";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};this.Qc=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.U=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var d=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return d=d?d[1]:null};this.Ge=function(){var a=this.U("uid",this.aa);null==
a?(a=this.Qc(),this.aa=this.aa+"&uid="+a):""==a&&(a=this.Qc(),this.aa=this.aa.replace("&uid=","&uid="+a));return a};this.oc=function(a,b,d,c){if(c&&c.insertBefore&&c.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=b[e];for(e in d)a.style[e]=d[e];c.insertBefore(a,c.firstChild);return a}return null};this.Wd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};
this.R=this.dvObj.CommonData.Scenario||this.Wd();this.M={X:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Y=this.dvObj.Enums.BrowserId;this.V=this.dvObj.Enums.TrafficScenario;this.Xa="default";this.dataObj=a;this.window=a.tagWindow||parent.window||window;this.c=null;this.sc=this.Pa=!1;this.lc=!0;this.interval=null;this.aa=this.Ie();this.Ba=this.Fe();a.serverSettings&&a.serverSettings.protocol&&a.serverSettings.protocol.indexOf("http");this.Z=window.he||this.window.he||
{interval:100,za:{"default":{time:null,Ja:["beforeunload","unload"],td:9E5}}};this.gd={};var c=null;this.T=window.ge||this.window.ge||{interval:1E3,$:6};var k=a&&a.vd?a.vd:!1;a=a&&a.wd?a.wd:!1;!1!==k&&!1!==a&&(this.T.interval=k,this.T.$=a,$dv.registerEventCall(this.impressionId,{Lf:this.T.interval,Mf:this.T.$}));k=this.b.Ua();this.ae={hb:12,Wb:10,Wa:30};this.N={Firefox:{W:115},Chrome:{W:89},Safari:{W:38},Explorer:{W:55},cf:500,Ua:k,Wa:30};var w=!1,r=0,g=[5,10,15];window.devicePixelRatio&&(this.N.Firefox.W=
0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.ja=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050,413,50,31]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800,20]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},
{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300,360]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360,50,100,480]},{w:1280,h:[100]},{w:640,h:[480,90,360]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},
{w:930,h:[180]},{w:980,h:[90,120]},{w:900,h:[240]},{w:275,h:[300]},{w:600,h:[400]},{w:168,h:[28]},{w:216,h:[36]},{w:292,h:[30]}];this.dataObj.spotXmode&&(this.ja.push({w:320,h:[240]}),this.ja.push({w:400,h:[300]}),this.ja.push({w:450,h:[338]}),this.ja.push({w:600,h:[800]}),this.ja.push({w:640,h:[360]}),this.ja.push({w:854,h:[480]}),this.ja.push({w:500,h:[375]}));this.ob=this.Ge();this.Vb=!1;this.Na=function(a,b){this.window.Jc||(this.window.Jc=[]);this.window.Jc.push({caller:a,Of:b})};this.startTime=
(new Date).getTime();this.Qd=4;this.wc=0;this.ec=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,errorlevel1:16,Jf:17,interval:32};this.Ub=!1;this.ud=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.f.qe();this.window.dv_logObject[this.ob]=a}this.b.a("ie16e")};this.Db=function(a){this.b.a("ie17");this.Db=this.Vb?function(a){this.f.od(a);this.ud()}:function(a){this.f.od(a)};this.Db(a)};this.rc=function(a,b){this.rc=
this.Vb?function(a,f){this.f.nd(a,f);this.ud()}:function(a,f){this.f.nd(a,f)};this.rc(a,b)};this.Ab=function(){this.b.a("s4");this.c=this.Qb.ke(this.T.$);!this.c&&this.R==this.V.CrossDomain&&this.b.ua(this.window)&&(this.T.$=0);if(this.c)this.tf(),this.f.hf(this.c),q||(l(this.c,"ad"),q=!0),p||this.R!=this.V.CrossDomain&&this.R!=this.V.SameDomain||(l(window.parent,"ifr"),p=!0),setTimeout(d,this.Qb.hc?10:50);else if(0<this.T.$)this.T.$--,this.uf(),setTimeout(this.le(),this.T.interval);else{try{this.R==
this.V.CrossDomain&&(this.b.$c(this.window,this.ja)||this.b.ua(this.window))?(this.c=this.b.ya(this.window),this.f.md()):this.R==this.V.SameDomain&&this.b.$c(this.window,this.ja)?(this.c=this.b.ya(window.parent),this.f.md(),this.$d()):this.T.$=-1}catch(a){this.T.$=-1}setTimeout(d,10)}this.b.a("s4e")};this.$d=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),d=b.length,c=0;c<d;c++)b[c].contentWindow==a&&(this.c=
b[c],this.window=a.parent);this.b.a("ff26e")};this.uf=function(){this.dataObj.btreg&&this.dataObj.Qa?this.f.yf():this.f.zf()};this.tf=function(){this.b.a("s9");this.Pa=!0;this.f.vf();this.b.a("s9e")};this.Rd=function(){this.dataObj.cb=this.U("adsrv",this.aa)||"";this.dataObj.btreg=this.U("btreg",this.aa)||"";this.dataObj.ed=this.U("plcid",this.aa)||"";"8"==this.dataObj.cb&&""==this.dataObj.btreg&&(this.dataObj.btreg=this.dataObj.plcid);this.dataObj.Qa=this.U("btadsrv",this.aa)||"";this.dataObj.Ac=
this.U("adid",this.aa)||"";this.dataObj.ob=this.ob;this.dataObj.Te=this.U("isbtregex",this.Ba)||"";this.dataObj.jb=this.U("ctx",this.aa)||"";this.dataObj.ib=this.U("cmp",this.aa)||"";this.dataObj.Ue=this.U("lomd",this.Ba)||"";this.dataObj.findclass=this.U("findclass",this.Ba)||"";this.dataObj.displaynon=this.U("displaynon",this.Ba)||"";this.dataObj.Fc=this.U("bsdvview",this.Ba)||"";var a=this.U("bttag",this.Ba)||"";this.dataObj.gb=0<a.length?a.split("|"):[];a=this.U("btattb",this.Ba)||"";this.dataObj.Ia=
0<a.length?a.split("|"):[]};this.fd=function(a){a=this.xb(a);return 0<a.length?{tagServiceResult:a.join(",")}:{}};this.xb=function(a){if(!this.dvObj)return[];for(var b=[],d=0;d<a.length;d++){var c=this.dvObj.pubSub.publish(a[d],this.impressionId)||null;null!=c&&b.push(c);window&&(c=this.dvObj.pubSub.publish(a[d],window.$frmId)||null,null!=c&&b.push(c))}return b};this.zd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.aa+="&TKH="+this.dataObj.serverSettings.TKH)};this.ee=
function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),d=b.length>>>0;if(0===d)return-1;var c=0;1<arguments.length&&(c=Number(arguments[1]),c!=c?c=0:0!=c&&Infinity!=c&&-Infinity!=c&&(c=(0<c||-1)*Math.floor(Math.abs(c))));if(c>=d)return-1;for(c=0<=c?c:Math.max(d-Math.abs(c),0);c<d;c++)if(c in b&&b[c]===a)return c;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.ee();this.zd();this.Rd();this.f=new G(this.Sd,this.ae,this.dataObj);
this.ga=h(this.dataObj,this.f);this.dataObj.isRTNsDisabled&&(this.xb=function(){return[]});this.Vb=this.window.dv_logObject?!0:!1;this.Af();this.Vd=new aa(this.dataObj,this.window,this.c,this.R,this.V,this.dvObj);this.Qb=new X(this.dataObj,this.ja,this.window,this.f,this.R,this.Vd);var a=window.parent;"589953"==this.dataObj.jb&&"587351"==this.dataObj.ib||"589953"==this.dataObj.jb&&"616389"==this.dataObj.ib||"polite"==this.dataObj.Ue?(setTimeout(e,15E3),this.b.Ja.add("load",function(){setTimeout(e,
1E3)},!1,a,!1)):e()}catch(b){var c=this;this.Ea(function(){c.Na("inViewManager",b);c.f.Za("inViewManager",b);c.ga.ca(c.logEvents.errorlevel1)},"inViewManager",b)}};this.ab=function(a){this.b.a("ie20");-6!=a.j&&(-3==a.j||-5!=a.j&&0>a.j&&-1==this.T.$)&&(this.tc(),this.ab=function(){})};this.tc=function(){this.ga.ca(this.logEvents.nonMeasurable);this.xb(["IABNotMeasuredImpression"]);this.tc=function(){}};this.Oa=function(a,b){a.b.a("ie21");if(0<=b.j||-5==b.j&&-1>=a.T.$){if(a.dvObj&&a.impressionId){a.b.a("ie23");
var c=a.fd(["IABMeasuredImpression"]);a.b.a("ie24");a.ga.ca(a.logEvents.startMeasure,c)}else a.ga.ca(a.logEvents.startMeasure);a.Ub=!0;a.Oa=function(){};a.ab=function(){}}a.b.a("ie22")};this.Nb=function(a){this.b.a("ie25");if(this.f.Mc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId?(this.b.a("ie28"),a=this.fd(["IABViewableImpression"]),this.b.a("ie29"),this.ga.ca(this.logEvents.iabViewable,a)):this.ga.ca(this.logEvents.iabViewable),w=!0,this.Nb=function(){};this.b.a("ie26")};this.be=
function(a){if(w&&this.f.Mc())for(r+=a,a=0;a<g.length;a++)null!=g[a]&&r>=1E3*g[a]&&(this.xb(["IABAdViewable"+g[a]+"Seconds"]),g[a]=null);else r=0};var b="hidden",t=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(var a in vis)if(vis[a]in document){b=vis[a];break}a=1==this.b.lb("fcs");var c=!1;try{this.b.Ta(this.window),c=!0}catch(d){}var e=!1;try{this.b.Ta(this.window.top),e=!0}catch(d){}var g=null,g=a&&c&&this.M.X==this.Y.IE?function(){var a=m.b.Ta(m.window);
m.R==m.V.OnPage&&(a=a&&m.lc);return a}:a&&e?function(){var a=!0,a=m.b.Ta(m.window.top);m.R==m.V.OnPage&&(a=a&&m.lc);return a}:"undefined"!==typeof document[b]?function(){return!m.window.document[b]}:e?function(){return m.b.Ta(m.window.top)}:function(){return!0};this.hasFocus=function(){try{return g()}catch(a){t++,5<=t&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.bc=function(a){var b=a.sa.ue();a.b.a("ie12");0>b.j&&this.f.Cb(Math.abs(b.j));null==this.c||-3==b.j||a.hasFocus()||
(b.j=0,this.f.Cb(9));a.b.a("ie13");return c=b};var v;this.Jb=function(a){var b;try{$uid&&dvObj&&dvObj.tags[$uid]&&dvObj.tags[$uid].getTimeDiff&&(b=dvObj.tags[$uid].getTimeDiff())}catch(c){}a.Z.interval=b-v||100;v=b;a.b.a("ie1");b=a.c?a.c.pb||a.window:a.window;a.sa.c=a.c;a.sa.window=b;a.b.a("ie2");b=a.bc(a);a.Pa&&(-1==b.j||-2==b.j)&&-1<=a.T.$&&(a.kd(a),a.Ab());a.b.a("ie3");-5==b.j&&(a.T.$--,a.f.pd(),a.Ma||(a.Ma=function(b){b=a.sa.sb(b);a.f.Ya(b)}));a.b.a("ie4");a.Ma&&0<b.j&&(a.Ma(b),a.Ma=null);a.b.a("ie5");
if(a.Pa&&!a.sc){a.sc=!0;var d=a.sa.sb(b);a.f.Ya(d)}-5==b.j&&-1<=a.T.$&&(a.kd(a),a.Ab(),b=a.bc(a),-5==b.j&&0<a.T.$&&a.f.qf());a.b.a("ie6");a.rc(b,a.Z.interval);a.b.a("ie7");a.Db(b);a.b.a("ie8");a.f.rd(b.ea);a.ab(b);a.b.a("ie9");a.Oa(a,b);a.b.a("ie10");a.Nb();a.b.a("ie11");a.be(a.Z.interval);a.b.a("ie12");return b};this.kd=function(a){a.Pa=!1;a.c=null;a.Qb.pf();a.sa.Je()};this.we=function(){this.b.a("s26");var a=this;return function(){try{a.Jb(a)}catch(b){a.Ea(function(){a.wc<a.Qd&&(a.wc++,a.Na("getIntervalCallback",
b),a.f.Za("getIntervalCallback",b),a.ga.ca(a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Pc=function(a){var b=this;return function(){b.Ea(function(){b.ga.ca(b.logEvents[a])},"getReportEventCallback")}};this.le=function(){var a=this;return function(){a.Ea(function(){a.Ab();a.c||a.f.Bb()},"getAdLocateCallback")}};this.Sa=function(){var a=this;return function(b){try{b||(b=a.window.event),a.lc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){a.Ea(function(){a.Na("getFocBluEventCallback",
c);a.f.Za("getFocBluEventCallback",c);a.ga.ca(a.logEvents.errorlevel1)},"getFocBluEventCallback",c)}}};this.Fd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.f.re().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*
c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.Ub,totalPageTime:(a.f.$b()-a.f.Ee())/1E3,notApplicableTime:a.f.Oc()/1E3}}catch(e){return{}}}}}catch(b){}};this.Gd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=c.j;0<=c.j&&c.s&&c.s.g&&(a.adWidth=c.s.g.o,a.adHeight=c.s.g.m);return a};a.VA.getAdElem=function(){return m.c}}}catch(b){}};this.Fd();this.start=
function(){this.b.a("s35");this.df(this);var a;this.Z&&this.Z.za&&this.Z.za[this.Xa]&&(a=this.Z.za[this.Xa].Ja);if(a)for(var b=a.length,c=0;c<b;c++)this.gd[a[c]]=this.Pc(a[c]),this.Ha(this.window,a[c],this.gd[a[c]]);this.Cf();this.Z&&this.Z.za&&this.Z.za[this.Xa]&&this.Z.za[this.Xa].td&&setTimeout(this.lf(),this.Z.za[this.Xa].td)};this.lf=function(){var a=this;return function(){a.Pc("timeout")();clearInterval(a.interval);a.ga.ca=function(){}}};this.df=function(a){try{var b=a.bc(a);-5==b.j&&(this.f.pd(),
this.Ma||(this.Ma=function(b){b=a.sa.sb(b);a.f.Ya(b)}));if(a.Pa)if(this.sc=!0,-5!=b.j){var c=a.sa.sb(b);a.f.Ya(c)}else a.f.Ya("true");a.f.rd(b.ea);var d=a.sa.ne(b,a.f.Oc());a.f.xf(d);a.f.qd(b.j);a.Db(b);a.ab(b);a.Oa(a,b)}catch(e){a.Ea(function(){a.Na("onStartReport",e);a.f.Za("onStartReport",e);a.ga.ca(a.logEvents.errorlevel1)},"onStartReport",e)}};this.Cf=function(){this.Ha(this.window,"blur",this.Sa());this.Ha(this.window,"focus",this.Sa());this.Ha(this.window.document,"click",this.Sa());this.Ha(this.window.document,
"mousedown",this.Sa());this.Ha(this.window.document,"mouseup",this.Sa())};this.Ha=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=function(){};this.Af=function(){this.b.a("ff24");this.R==this.V.CrossDomain?this.b.ua(this.window)||this.b.jc(this.window)||this.b.tb()||this.b.ub(this.R,this.M,this.dvObj)||(this.M.X!=this.Y.Firefox&&
this.M.X!=this.Y.IE?this.f.Bf():this.M.X==this.Y.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.f.pc()):window.document.body.getBoundingClientRect||this.f.pc();this.ec=this.f.Gc();this.b.a("ff24e")};this.Ea=function(a,b,c){try{a()}catch(d){try{0<this.cd&&(this.cd--,a=c||d,b=b||"unknown caller",this.Na(b,a),this.f.Za(b,a),this.ga.ca(m.logEvents.errorlevel1))}catch(e){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(a){(new dv_CustomClientViewAssureService(a)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var Y=[window.$dvbs,window.$dvbsr],Z=0;Z<Y.length;Z++){var dvObj=Y[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs676");
if(tagObject){var serviceParams=tagObject.services.avs676;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(a){};
